fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      description
    }
    ... on PageBlocksProjects {
      heading
      subheading
      items {
        __typename
        image
        name
        description
        href
      }
    }
  }
}

fragment PostParts on Post {
  title
  body
}
